# Artificial Intelligence - Fall 2024 - Laboratory 02:Python Introduction part II


##### Review

The following formula computes a _Z score_ and measures how far a single raw data value is from the population mean.

\begin{equation*}
z = \frac{X - \mu }{\sigma }
\end{equation*}

where:
* **_X_** is a single raw data value
* `mu` is the population mean
* `sigma` is the population standard deviation

To find the standard deviation, the equation below comes in hand:

\begin{equation*}
\sigma = \sqrt{\frac{\sum \left | X - \mu \right |^{2}}{N}}
\end{equation*}

where **_N_** is the number of data points in the population.

**a.** Using `sum()` and `list comprehension`, compute the mean and the standard deviation for the population defined below:

In [5]:
data =  [4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]
print(data)

[4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]


In [7]:
import math 

In [10]:
# Your implementation here:
mean = sum(data) / len(data)
std = math.sqrt(sum([(X - mean)**2 for X in data]) / len(data))

print(mean)
print(std)

12.616666666666667
7.167441818544622


**b.** Define the `z_score()` function and implement the mathematical expression. The obtained values should be stored in a _z score_ values list and rounded to 3 decimals.

In [11]:
# Your implementatio here:
def z_score(X, mu, std):
    return (X - mu) / std

In [14]:
z_score_all = [round(z_score(X, mean, std), 3) for X in data]

print(z_score_all)

[-1.132, -1.063, -0.993, -0.923, -0.888, -0.784, 0.367, 0.751, 0.814, 1.17, 1.232, 1.449]


**c.** Add the corresponding elongation of each raw data value into a dictionary.

In [19]:
# Your implementatio here:
elongation_dict = {X: round(z_score(X, mean, std), 3) for X in data}
print(elongation_dict)

{4.5: -1.132, 5: -1.063, 5.5: -0.993, 6: -0.923, 6.25: -0.888, 7: -0.784, 15.25: 0.367, 18: 0.751, 18.45: 0.814, 21: 1.17, 21.45: 1.232, 23: 1.449}


In [124]:
class ScientificConference:
    
    def __init__(self, name, year, papers = None):

        self.name = name
        self.year = year
        self.papers = papers if papers is not None else {}
    
    def add_manuscript(self, title, researcher):
        self.papers[researcher] = [title]           
    
    def __str__(self):
        
        result = f'{self.name} {self.year}: \n'
            
        for author, papers in self.papers.items():
            result += f'{author}: {", ".join(papers)} \n'
        
            
        return result
        

### Task 0

**a.** Define two new `instances` of the `class ScientificConference` and return their representations.

Your output should look like:

`Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.`

_Hint:_ `instance.attribute` helps you extracting a certain property.

In [125]:
# Your implementation here
conference1 = ScientificConference('ICML', 2021)
conference2 = ScientificConference('NeurIPS', 2021)

print(f"Proposals for {conference1.name} and {conference2.name} conferences will be accepted until the end of November {conference1.year}.")



Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.


**b.** Create a new attribute for the `class ScientificConference`, which is a dictionary passed as a parameter to the instances of the class and holds all of the papers of the conference.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

_Please handle duplicate entries by removing them!_

**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. Please consider using the _researcher_ as a `key` and the _title_ as `values`.

In [126]:
conference1.add_manuscript("ManuscriptX", 'John')
conference1.add_manuscript("Manuscriiiipt", 'Jane' )

conference2.add_manuscript("Manuscripttt", 'Jim')
conference2.add_manuscript("Maaaanuuuuscript", 'Jack')

print(conference1)

ICML 2021: 
John: ManuscriptX 
Jane: Manuscriiiipt 



### Task 1

**a.** Define the class `Person` which stores the `title`, `name` and `surname` of a person.

The _tuple_ `allowed_titles` is a class variable which helps to verify if the title of a person is "Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS" or "Computer Scientist".

An error is returned if the title is not valid.

Use `__str__` defined below:

```python
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
```

**b.** Create two instances of the class Person and verify if the following entries are valid:

* _Mr Ian Goodfellow_,
* _SeniorResearcher Tomas Mikolov._

In [89]:
# Your implementation here
class Person:

    allowed_titles = ("Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS", "Computer Scientist")

    def __init__(self, title, name, surname):

        if title not in Person.allowed_titles:
            raise ValueError("The title isn't right")
            
        self.title = title
        self.name = name
        self.surname = surname

    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
        

In [61]:
person1 = Person("Mr", "Ian", "Goodfellow")

In [62]:
person2 = Person("SeniorResearcher", "Tomas", "Mikolov")

ValueError: The title isn't right

### Task 2

In `ScientificConference` we have been using the paper parameter as a string, but this concept requires a detailed structure.

Introduce a new class, `Paper`, which has the following attributes:

* `authors`, 
* `title`, 
* `a_id`,
* `year`, 
* `status` (published or in development), 
* `peer_rating` (Excellent, Good, Fair, Poor, Barely Acceptable, Unacceptable).

In [69]:
class Paper:

    allowed_status = ("published", "in development")

    allowed_peer_rating = ("Excellent", "Good", "Fair", "Poor", "Barely Acceptable", "Unacceptable")
    
    def __init__(self, authors, title, a_id, status, year, peer_rating):
        
        if status not in Paper.allowed_status:
            raise ValueError("The status isn't right")

        if peer_rating not in Paper.allowed_peer_rating:
            raise ValueError("The peer rating isn't right")

        self.authors = authors
        self.title = title
        self.a_id = a_id
        self.status = status
        self.year = year
        self.peer_rating = peer_rating
        

    def __str__(self):
        return  f'{self.title}, {", ".join([author for author in self.authors])} et al. ({self.year}), a_id: '\
                f'{self.a_id}, status: {self.status}, rating: {self.peer_rating}'

In [70]:
paper1 = Paper(
    authors=["Yann LeCun", "Yoshua Bengio", "Geoffrey Hinton"],
    title="Deep Learning",
    a_id="https://doi.org/10.1038/nature14539",
    year=2015,
    status="published",
    peer_rating="Excellent"
)

print(paper1)

Deep Learning, Yann LeCun, Yoshua Bengio, Geoffrey Hinton et al. (2015), a_id: https://doi.org/10.1038/nature14539, status: published, rating: Excellent


## Inheritence

In Object-Oriented programming, this concept enables us to transfer the methods and the properties of a class to another class.

### Task 3

Create a class named `Researcher`, which inherits the properties and methods from the `Person` class. Besides, this class has an additional parameter, `papers` which is `None` by default.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `[]` instead.

```python
class Researcher(Person):
    def __init__('Add arguments'):
        super().__init__(title, name, surname)
```

In [100]:
class Researcher(Person):
    
    def __init__(self, title, name, surname, papers = None):
        super().__init__(title, name, surname)
        self.papers = papers if papers is not None else []

    def add_paper(self, paper):
        
        self.papers.append(paper)

    def __str__(self):
        
        paper_list = ', '.join(self.papers) if self.papers else "-"
        
        return f"{super().__str__()}  with papers: {paper_list}"
        

In [101]:
researcher1 = Researcher("Senior Researcher", "Tomas", "Mikolov")
print(researcher1)

Senior Researcher Mikolov Tomas  with papers: -


### Task 4

Consider the following scientists:

1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yann LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.

_Note:_ Let us consider "Mr" as a default title for the researchers without a specific caption. Also, for the id of a paper, please use only integers from the provided links.

**a.** Define the next 5 scientists and use them in your `paper` objects.

**b.** Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
_Hint:_ Use `self.co_authored = False` inside the `__init__` function.

**c.** Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`print_papers(researcher2.get_collab(researcher3))` should output:

_Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

_Note:_ This function helps you to print the papers from a given list.

```python
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)
```

**d.** What are the papers written by Yoshua Bengio?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent`

`Paper On the difficulty of training recurrent neural networks, Mr Razvan Pascanu et al. (2013), a_id: 5063, status: published, rating: Excelent`

**e.** Did he ever co-author a paper?

**f.** Which papers are published by Yann LeCun?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Good`

In [103]:
class Paper:
    
    def __init__(self, authors, title, a_id, year, status, peer_rating):
        self.authors = authors  
        self.title = title  
        self.a_id = a_id  
        self.year = year 
        self.status = status  
        self.peer_rating = peer_rating  
    
    def __str__(self):
        return (f'{self.title}, {", ".join(self.authors)} et al. ({self.year}), '
                f'a_id: {self.a_id}, status: {self.status}, rating: {self.peer_rating}')
        

In [104]:
class Researcher(Person):
    
    def __init__(self, title, name, surname, papers=None):
        
        super().__init__(title if title else "Mr", name, surname) 
        
        self.papers = papers if papers is not None else []
        self.co_authored = False

    def add_paper(self, paper):
        self.papers.append(paper)

    def verify_co_authorship(self, other_researcher):
        
        for paper in self.papers:
            
            if any(author in other_researcher.get_full_name() for author in paper.authors):
                self.co_authored = True
                return True
                
        return False

    def get_collab(self, other_researcher):
        
        collab_papers = []
        
        for paper in self.papers:
            if other_researcher.get_full_name() in paper.authors:
                collab_papers.append(paper)
                
        return collab_papers

    def get_full_name(self):
        return f"{self.title} {self.name} {self.surname}"

In [105]:
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)

In [107]:
researcher1 = Researcher("Computer Scientist", "Yann", "LeCun")
researcher2 = Researcher("Senior Researcher", "Yoshua", "Bengio")
researcher3 = Researcher("Mr", "Ian", "Goodfellow")
researcher4 = Researcher("Mr", "Geoffrey", "Hinton")
researcher5 = Researcher("Mr", "Razvan", "Pascanu")

In [108]:
paper1 = Paper(
    authors=[researcher1.get_full_name(), researcher2.get_full_name(), researcher4.get_full_name()],
    title="Deep Learning",
    a_id=14539,
    year=2015,
    status="published",
    peer_rating="Excellent"
)

paper2 = Paper(
    authors=[researcher5.get_full_name(), researcher3.get_full_name(), researcher2.get_full_name()],
    title="On the difficulty of training recurrent neural networks",
    a_id=5063,
    year=2013,
    status="published",
    peer_rating="Excellent"
)

paper3 = Paper(
    authors=[researcher3.get_full_name(), researcher2.get_full_name()],
    title="Generative Adversarial Nets",
    a_id=5423,
    year=2015,
    status="published",
    peer_rating="Excellent"
)

paper4 = Paper(
    authors=[researcher1.get_full_name()],
    title="Handwritten Digit Recognition with a Back-Propagation Network",
    a_id=293,
    year=1989,
    status="published",
    peer_rating="Excellent"
)

paper5 = Paper(
    authors=[researcher4.get_full_name()],
    title="Gated Softmax Classification",
    a_id=3895,
    year=2010,
    status="published",
    peer_rating="Good"
)

In [109]:
researcher1.add_paper(paper1)
researcher1.add_paper(paper4)

researcher2.add_paper(paper1)
researcher2.add_paper(paper2)
researcher2.add_paper(paper3)

researcher3.add_paper(paper2)
researcher3.add_paper(paper3)

researcher4.add_paper(paper1)
researcher4.add_paper(paper5)

researcher5.add_paper(paper2)

In [110]:
# d. papers written by Yoshua Bengio
print_papers(researcher2.papers)

Deep Learning, Computer Scientist Yann LeCun, Senior Researcher Yoshua Bengio, Mr Geoffrey Hinton et al. (2015), a_id: 14539, status: published, rating: Excellent
On the difficulty of training recurrent neural networks, Mr Razvan Pascanu, Mr Ian Goodfellow, Senior Researcher Yoshua Bengio et al. (2013), a_id: 5063, status: published, rating: Excellent
Generative Adversarial Nets, Mr Ian Goodfellow, Senior Researcher Yoshua Bengio et al. (2015), a_id: 5423, status: published, rating: Excellent


In [113]:
# e. yoshua bengio as coauthor
print(researcher2.verify_co_authorship(researcher3))

True


In [114]:
# f. papers published by yann lecun
print_papers(researcher1.papers)

Deep Learning, Computer Scientist Yann LeCun, Senior Researcher Yoshua Bengio, Mr Geoffrey Hinton et al. (2015), a_id: 14539, status: published, rating: Excellent
Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Excellent


### Task 5 

Consider an updated version of the `ScientificConference` class, which should have a modified version of the function `add_manuscript`.

Use the `status` and the `peer_rating` variables as a **threshold** to add papers in your `papers` dictionary. The conferences will only be accepting `Excelent` papers. For this case, the dictionary has the year of the paper as `key`, and the `values` are stored as a tuple of `(researcher, manuscript)`. For the papers which don't satisfy this condition, the message _"Please review your submission."_ is displayed.

For papers submitted in 2015, when printing the conference, the `str` function should output:

```
NeurIPS 2020: 
2015: 
Mr Ian Goodfellow: Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), id: 5423, status: published, rating: Excelent 
Computer Scientist Yann LeCun: Deep Learning, Computer Scientist Yann LeCun et al. (2015), id: 14539, status: published, rating: Excelent
```

In [134]:
class ScientificConferenceUpdate:
    
    def __init__(self, name, year, papers = None):
        
        self.name = name
        self.year = year
        self.papers = {}
        
    
    def add_manuscript(self, manuscript, researcher):
        if manuscript.peer_rating == "Excellent": 
            if manuscript.year not in self.papers:
                self.papers[manuscript.year] = []

            self.papers[manuscript.year].append((str(researcher), manuscript))
        
        
    def __str__(self):
        result = self.name + ' ' + str(self.year) + ': \n'
        for year, papers in self.papers.items():
            result += f'{year}: \n'
            for (author, paper) in papers: 
                result += f'{author}: {paper} \n'
        return result

In [135]:
conference3 = ScientificConferenceUpdate("ConferenceX", 2020)

In [136]:
paper1 = Paper(
    authors=[str(researcher1), str(researcher2), str(researcher4)],
    title="Deep Learning",
    a_id=14539,
    year=2015,
    status="published",
    peer_rating="Excellent"
)

paper2 = Paper(
    authors=[str(researcher3), str(researcher2)],
    title="Generative Adversarial Nets",
    a_id=5423,
    year=2015,
    status="published",
    peer_rating="Excellent"
)

In [137]:
conference3.add_manuscript(paper1, researcher1)
conference3.add_manuscript(paper2, researcher3)

In [138]:
print(conference3)

ConferenceX 2020: 
2015: 
Computer Scientist LeCun Yann: Deep Learning, Computer Scientist LeCun Yann, Senior Researcher Bengio Yoshua, Mr Hinton Geoffrey et al. (2015), a_id: 14539, status: published, rating: Excellent 
Mr Goodfellow Ian: Generative Adversarial Nets, Mr Goodfellow Ian, Senior Researcher Bengio Yoshua et al. (2015), a_id: 5423, status: published, rating: Excellent 

